databases:
  - name: money_order_app
    databaseName: money_order_app
    user: money_order_app_user

services:
  - type: web
    name: money_order_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: money_order_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

