databases:
  - name: money_order_app
    databaseName: money_order_app_a06p
    user: money_order_app_a06p_user

services:
  - type: web
    name: money_order_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: money_order_app_a06p
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

